HotelManagement/Models/SMTP.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMTP
    {
        public string To { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

HotelManagement/Controllers/SMTPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HotelManagement.Models;
using System.Net.Mail;
using System.Net;



namespace HotelManagement.Controllers
{
    public class SMTPController : Controller
    {
        //GET: EmailSetup
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(HotelManagement.Models.SMTP model)
        {
            MailMessage mm = new MailMessage("guestreservationnotification@gmail.com", model.To);
            mm.Subject = "Welcome to Royal Grand Hotel";
            mm.Body = "Your Room ID is Booked Successfully" +
                "Have a Nice Stay.";
            mm.IsBodyHtml = false;



            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;
            NetworkCredential nc = new NetworkCredential("guestreservationnotification@gmail.com", "miqxnurgwkwdqyir");
            smtp.UseDefaultCredentials = true;
            smtp.Credentials = nc;
            smtp.Send(mm);



            ViewBag.Message = "Mail has been send Successfully";
            return View();
        }
    }
}

HotelManagement/Views/SMTP/Index.cshtml
@model HotelManagement.Models.SMTP

@{
    ViewBag.Title = "Index";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "SMTP", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
           
         
            <font style="font-family:'Times New Roman', Times, serif; color:antiquewhite; font-size:larger">
                <b>  <h2>Guest Notification form</h2></b>

                <hr />
                <table>
                    <tr>
                        <td style="width:80px">
                            To:
                        </td>
                        <td>@Html.TextBoxFor(model => model.To)</td>
                    </tr>
                  
               
                    <tr>

                        <td>
                            <input type="submit" value="Send" />
                        </td>

                    </tr>
                </table>
                <br />
                <span style="color:blue">@ViewBag.Message</span>
                </font>
                }
</div>
</body>
</html>