HotelManagement/Controllers/BILLController.cs
using HotelManagement.Models;
using HotelManagement.Models.DAL;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web.Mvc;

namespace HotelManagement.Controllers
{
    public class BILLController : Controller
    {
        // GET: MyCustomer

        private _IAllRepository<BILL> interfaceobj;

        public BILLController()
        {
            this.interfaceobj = new AllRepository<BILL>();
        }
        public ActionResult Index()
        {
            return View(from m in interfaceobj.GetModel() select m);
            HotelManagementDBEntities2 db = new HotelManagementDBEntities2();

            Reservation res = new Reservation();
            BILL bill = new BILL();
            if (res.Reservation_ID == bill.Reservation_ID)
            {

                if (EntityFunctions.DiffDays(res.CheckOUT_Date, res.CheckIN_Date) == 1)
                {
                    ViewBag.Total = 2000;
                }
                else if (EntityFunctions.DiffDays(res.CheckOUT_Date, res.CheckIN_Date) == 2)
                {
                    ViewBag.Total = 4000;
                }
                else if (EntityFunctions.DiffDays(res.CheckOUT_Date, res.CheckIN_Date) == 3)
                {
                    ViewBag.Total = 6000;
                }

            }

        }
        public ActionResult Create()
        {

            HotelManagementDBEntities2 db = new HotelManagementDBEntities2();

            var list = new List<string>();
            list.Add("Cash");
            list.Add("Online");
            ViewBag.payment = new SelectList(list, "Transaction_Type");
           ;



            var ReservationID = db.Reservations.ToList();
            ViewBag.ResevationID = new SelectList(ReservationID, "Reservation_ID", "Reservation_ID");

            return View();
        }
        [HttpPost]
        public ActionResult Create(BILL collection)
        {
            try
            {
                interfaceobj.InsertModel(collection);
                interfaceobj.Save();
                return RedirectToAction("Index");
             

                

            }

            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {

            HotelManagementDBEntities2 db = new HotelManagementDBEntities2();
            var list = new List<string>();
            list.Add("Cash");
            list.Add("Online");
            ViewBag.payment = new SelectList(list, "Transaction_Type");

            var ReservationID = db.Reservations.ToList();
            ViewBag.ResevationID = new SelectList(ReservationID, "Reservation_ID", "Reservation_ID");

            BILL c = interfaceobj.GetModelById(id);
            return View(c);
        }
        [HttpPost]
        public ActionResult Edit(int id, BILL collection)
        {
            try
            {
                interfaceobj.UpdateModel(collection);
                interfaceobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            BILL D = interfaceobj.GetModelById(id);
            return View(D);
        }
        [HttpPost]
        public ActionResult Delete(int id, BILL collection)
        {
            try
            {
                interfaceobj.DeleteModel(id);
                interfaceobj.Save();
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
    }
}

HotelManagement/Controllers/DASHBOARDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;

namespace HotelManagement.Controllers
{
    public class DASHBOARDController : Controller
   
        {
            // GET: DashBoard

            public ActionResult IndexReceptionist()
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("IndexReceptionist", "Login");
                }
                else
                {
                return View();
            }
            }
            public ActionResult LogoutReceptionist()
            {
                //means current session destroy
                Session.Abandon();
                return RedirectToAction("IndexReceptionist", "Login");
            }
            public ActionResult IndexManager()
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("IndexManager", "Login");
                }
                else
                {
                    return View();
                }
            }
            public ActionResult LogoutManager()
            {
                //means current session destroy
                Session.Abandon();
                return RedirectToAction("IndexManager", "Login");
            }
            public ActionResult IndexOwner()
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("IndexOwner", "Login");
                }
                else
                {
                    return View();
                }
            }
            public ActionResult LogoutOwner()
            {
                //means current session destroy
                Session.Abandon();
                return RedirectToAction("IndexOwner", "Login");
            }
        }
    }

HotelManagement/Controllers/ROOMController.cs
using HotelManagement.Models;
using HotelManagement.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelManagement.Controllers
{
    public class ROOMController : Controller
    {

        // GET: GUEST
        private _IAllRepository<ROOM> interfaceobj;
        public ROOMController()
        {
            this.interfaceobj = new AllRepository<ROOM>();

        }
        public ActionResult Index()
        {
            return View(from m in interfaceobj.GetModel() select m);
        }
        public ActionResult Index1()
        {
            return View(from m in interfaceobj.GetModel() select m);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ROOM collection)
        {
            try
            {
                interfaceobj.InsertModel(collection);
                interfaceobj.Save();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            ROOM g = interfaceobj.GetModelById(id);

            return View(g);
        }
        [HttpPost]
        public ActionResult Edit(int id, ROOM collection)
        {
            try
            {
                interfaceobj.UpdateModel(collection);
                interfaceobj.Save();
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            ROOM D = interfaceobj.GetModelById(id);
            return View(D);
        }
        [HttpPost]
        public ActionResult Delete(int id, ROOM collection)
        {
            try
            {
                interfaceobj.DeleteModel(id);
                interfaceobj.Save();
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
    }
}

HotelManagement/Views/DASHBOARD/IndexManager.cshtml
    @{
        ViewBag.Title = "Manager";
    }
<font style="font-family:'Times New Roman', Times, serif; color:antiquewhite; font-size:larger">
    <b> <h2>Manager</h2></b>
    

        @{
            ViewBag.Title = "IndexManager";
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
       
        @{
            ViewBag.Title = "IndexManager";
        }
        @Html.Raw(TempData["LoginSuccessMessage"])
        
        <h3> Welcome @Session["Staff_name"]</h3>
        <p><h3>
    <button><li>@Html.ActionLink("Receptionist", "Index", "Receptionist")</li></button>
    <button> <li>  @Html.ActionLink("Room", "Index", "Room") </li></button>
    <button><li>  @Html.ActionLink("Logout", "LogoutManager", "Dashboard") </li></button>
    <button> <li>@Html.ActionLink("BACK", "LogoutReceptionist", "DASHBOARD")</li></button>
</h3>
        </p>
 

    </font>

HotelManagement/Views/DASHBOARD/IndexOwner.cshtml
    @{
        ViewBag.Title = "Owner";
    }
    <font style="color:cornsilk">
        <h2>Owner</h2>
        
        @{
            ViewBag.Title = "IndexOwner";
        }

        @Html.Raw(TempData["LoginSuccessMessage"])

       

        <h3> Welcome @Session["owner_Email"]</h3>
        <p>
            <button><h3> <li>@Html.ActionLink("Manager", "Index", "MANAGER")</li></h3></button>

            <button><h3> <li>@Html.ActionLink("Receptionist", "Index1", "RECEPTIONIST")</li></h3></button>

            <button><h3> <li>@Html.ActionLink("Department", "Index", "DEPARTMENT")</li></h3></button>

            <button><h3><li>@Html.ActionLink("Room", "Index1", "ROOM")</li></h3></button>

            <button><h3> <li>@Html.ActionLink("BillDetals", "Index", "BILL")</li></h3></button>

            <button><h3><li>@Html.ActionLink("Logout", "LogoutOwner", "DASHBOARD")</li></h3></button>

        </p>
    </font>

HotelManagement/Views/DASHBOARD/IndexReceptionist.cshtml
@{
    ViewBag.Title = "IndexReceptionist";
}

<font style="font-family:'Times New Roman', Times, serif; color:antiquewhite; font-size:larger">
    <b> <h2>Receptionist</h2></b>
    @{
        ViewBag.Title = "IndexReceptionist";
    }

    @Html.Raw(TempData["LoginSuccessMessage"])

    @Html.Raw(TempData["Request"])

    @Html.Raw(TempData["Reply"])


    <h4> Welcome @Session["Staff_name"]</h4>
    <p>
        <button> <h3><li>@Html.ActionLink("Guest", "Index", "GUEST")</li></h3></button>

        <button> <h3> <li>@Html.ActionLink("Reservation", "Index", "RESERVATION")</li></h3></button>

        <button> <h3> <li>@Html.ActionLink("Room", "Index", "ROOM")</li></h3></button>

        <button> <h3><li>@Html.ActionLink("Logout", "Index", "Homee")</li></h3></button>

        <button> <h3><li>@Html.ActionLink("BACK", "LogoutReceptionist", "DASHBOARD")</li></h3></button>
    </p>

   